// AUTO-GENERATED by openapi-typescript — do not edit manually.
// Run `npm run generate-types` with the .NET API running at http://localhost:5025
export type paths = Record<string, unknown>;
export type components = { schemas: Record<string, unknown> };
